/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness / readiness smoke check.
         * @description Unauthenticated. Used by operators and sibling `/health` aggregation (Phase 4).
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List catalog apps with dependency graph (R-01).
         * @description Returns the authoritative catalog (`catalog/apps.json`) so the installer
         *     wizard can present selectable apps and resolve dependency order. Read-only;
         *     no audit event (audit-trail §1).
         */
        get: operations["listCatalogApps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a new install session (R-01, R-08).
         * @description Creates an install session in status `in_progress`. The wizard groups all
         *     subsequent steps under `installSessionId`.
         *
         *     **Audit:** emits `install_session.started`
         *     (`before_json` NULL → `after_json` session snapshot; includes tier and
         *     catalog revision) per audit-trail §4.
         */
        post: operations["startInstallSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install-sessions/{installSessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID of the install session (maps to `install_session_id`).
                 * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
                 */
                installSessionId: components["parameters"]["InstallSessionId"];
            };
            cookie?: never;
        };
        /**
         * Fetch one install session.
         * @description Read-only; no audit event (audit-trail §1).
         */
        get: operations["getInstallSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install-sessions/{installSessionId}/app-selection": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID of the install session (maps to `install_session_id`).
                 * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
                 */
                installSessionId: components["parameters"]["InstallSessionId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the selected app set for a session (R-01).
         * @description Idempotent replacement of the selected catalog ids. The server resolves
         *     and enforces dependency order (e.g. selecting `nene-clear` requires
         *     `nene-invoice`) and rejects non-`installable` apps.
         *
         *     **Audit:** emits `app_selection.changed`
         *     (`before_json` prior selection → `after_json` new selection, with full
         *     catalog id list and dependency resolution) per audit-trail §4.
         */
        put: operations["updateAppSelection"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install-sessions/{installSessionId}/disclaimer-acceptance": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID of the install session (maps to `install_session_id`).
                 * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
                 */
                installSessionId: components["parameters"]["InstallSessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record operator acceptance of the disclaimer (R-04).
         * @description Operator must accept the binding disclaimer before the install can
         *     complete. `acceptedLabel` (e.g. operator email) is stored as the audit
         *     `actor_label` display fallback only — never a secret.
         *
         *     **Audit:** emits `disclaimer.accepted`
         *     (`before_json` NULL → `after_json` acknowledgment snapshot with version
         *     string, timestamp, operator label) per audit-trail §4.
         */
        post: operations["acceptDisclaimer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install-sessions/{installSessionId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID of the install session (maps to `install_session_id`).
                 * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
                 */
                installSessionId: components["parameters"]["InstallSessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize an install session (R-04, R-05, R-08).
         * @description Transitions the session to `completed`. Pre-conditions: disclaimer
         *     accepted (R-04) and at least one installable app selected. On success the
         *     server writes the install manifest (no secrets, R-05) and links it via
         *     `installManifestId`.
         *
         *     **Audit:** emits `install_session.completed`
         *     (`before_json` in-progress → `after_json` completed snapshot) and
         *     `manifest.created`. The completed `after_json` SHOULD reference the same
         *     content as the manifest (hash or embedded copy) per audit-trail §4, §8.
         */
        post: operations["completeInstallSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install-sessions/{installSessionId}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID of the install session (maps to `install_session_id`).
                 * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
                 */
                installSessionId: components["parameters"]["InstallSessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark an install session as failed (R-08).
         * @description Records a terminal failure (e.g. database provisioning error). `failureCode`
         *     is required and is persisted to the audit `metadata_json.failure_code`.
         *
         *     **Audit:** emits `install_session.failed`
         *     (`before_json` in-progress → `after_json` failed snapshot;
         *     `metadata_json.failure_code` required) per audit-trail §4.
         */
        post: operations["failInstallSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/installed-apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List applications installed through the suite (R-06).
         * @description Powers the apex launcher. Returns installed apps with their public URL and
         *     an optional SSOT role label (`docs/explanation/terminology.md` §7), derived
         *     from each app's catalog `provides`. Read-only; no audit event.
         */
        get: operations["listInstalledApps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suite-audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the orchestration audit trail (R-08, read-only).
         * @description Paginated, append-only orchestration audit events (before/after snapshots).
         *     Domain audit stays in each sibling product. Phase 1 is **read-only**; no
         *     create/update/delete (audit-trail §7 — append-only, hard delete forbidden).
         *     Operator-authenticated.
         *
         *     Field names map to `schema/suite-audit-event.schema.json` per the mapping
         *     table in `info.description` (`before`→`before_json`, etc.).
         */
        get: operations["listSuiteAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current operator for the presented token.
         * @description Returns the operator associated with the bearer token, so the apex shell
         *     can validate the session on load and render the signed-in operator.
         *     Read-only; no audit event.
         */
        get: operations["getAuthSession"];
        put?: never;
        /**
         * Log in — create an apex operator session.
         * @description Authenticates an operator by email and password and returns a short-lived
         *     apex JWT plus the operator profile. Unauthenticated. Invalid credentials
         *     return 401 `invalid-credentials` (not 422) so the apex shell can show a
         *     single "invalid email or password" message without revealing which field failed.
         */
        post: operations["createAuthSession"];
        /**
         * Log out — end the apex operator session.
         * @description Ends the current session. JWTs are stateless in Phase 1, so clients MUST
         *     discard the token; server-side revocation MAY be added in Phase 2.
         */
        delete: operations["deleteAuthSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Crockford base32 ULID (26 chars). Matches `schema/*.schema.json`.
         * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
         */
        Ulid: string;
        /**
         * @description Catalog app id (`docs/explanation/terminology.md` §2.1).
         * @example nene-invoice
         */
        CatalogId: string;
        /** @description Apex operator identity. No password or secret material. */
        Operator: {
            id: components["schemas"]["Ulid"];
            /** Format: email */
            email: string;
            displayName?: string | null;
        };
        CreateAuthSessionRequest: {
            /** Format: email */
            email: string;
            /** @description Never logged, stored in plaintext, or echoed in audit/manifest. */
            password: string;
        };
        AuthSession: {
            /** @description Apex operator JWT (bearer). Present it as the Authorization: Bearer header. */
            token: string;
            /** Format: date-time */
            expiresAt: string;
            operator: components["schemas"]["Operator"];
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @description Reflects `NENE_SUITE_MODE` (ADR 0004). */
            suiteMode: boolean;
            /** Format: date-time */
            time: string;
        };
        /** @description One catalog entry (mirrors `catalog/apps.json`; `installEntry` ↔ `install_entry`). */
        CatalogApp: {
            id: components["schemas"]["CatalogId"];
            /** @description Display name (terminology §1, exact spelling, e.g. "NeNe Invoice"). */
            name: string;
            /** @description `owner/repo` or null for unannounced apps. */
            repository?: string | null;
            path?: string;
            /** @enum {string} */
            status: "planned" | "installable" | "deprecated";
            requires: components["schemas"]["CatalogId"][];
            /** @description Capability tokens (terminology §2.3), e.g. `billing-api`. */
            provides: string[];
            /** @description Sibling installer entry path (`install_entry` in catalog JSON). */
            installEntry?: string;
            /**
             * @description Per-app DB env prefix (`database.env_prefix` in catalog JSON).
             * @example NENE_INVOICE_DB_
             */
            databaseEnvPrefix?: string;
        };
        CatalogAppList: {
            version: number;
            apps: components["schemas"]["CatalogApp"][];
        };
        /**
         * @description Lifecycle state (PHP `InstallSessionStatus`; HTTP value is snake_case).
         * @enum {string}
         */
        InstallSessionStatus: "in_progress" | "completed" | "failed";
        /**
         * @description Deployment tier (terminology §11). Phase 1 ships **Tier B** (Docker / VPS)
         *     only; **Tier A** (shared hosting) follows in Phase 3 and will extend this enum.
         * @enum {string}
         */
        Tier: "B";
        /** @description Installer wizard run. Persisted in the `nene_suite` control DB (no secrets). */
        InstallSession: {
            id: components["schemas"]["Ulid"];
            /** @description Matches `NENE_SUITE_ID` / manifest `suite_id`. */
            suiteId: components["schemas"]["Ulid"];
            status: components["schemas"]["InstallSessionStatus"];
            tier: components["schemas"]["Tier"];
            /** @description Pinned `catalog/apps.json` `version` at session start. */
            catalogRevision: number;
            /** @description Catalog ids selected, dependency-resolved and ordered. */
            selectedApps: components["schemas"]["CatalogId"][];
            disclaimerAccepted: boolean;
            /** Format: date-time */
            disclaimerAcceptedAt?: string | null;
            /** @description Federation UUID (`org_external_id`) — IT federation only, not tax registration. */
            orgExternalId?: components["schemas"]["Ulid"] | null;
            orgDisplayName?: string | null;
            /** @description Set when `status` is `completed`; links to the written install manifest. */
            installManifestId?: components["schemas"]["Ulid"] | null;
            /** @description Set when `status` is `failed`; mirrors audit `metadata_json.failure_code`. */
            failureCode?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt?: string | null;
        };
        StartInstallSessionRequest: {
            tier: components["schemas"]["Tier"];
            /** @description Optional initial selection; can also be set later via `updateAppSelection`. */
            selectedApps?: components["schemas"]["CatalogId"][];
            orgDisplayName?: string;
        };
        UpdateAppSelectionRequest: {
            /**
             * @description Catalog ids the operator wants. The server resolves dependencies
             *     (adds required apps) and rejects non-`installable` entries.
             */
            selectedApps: components["schemas"]["CatalogId"][];
        };
        AcceptDisclaimerRequest: {
            /**
             * @description Version string of the accepted disclaimer copy.
             * @example 2026-05-29
             */
            disclaimerVersion: string;
            /** @description Operator display label (e.g. email) stored as audit `actor_label`. No secrets. */
            acceptedLabel?: string;
        };
        FailInstallSessionRequest: {
            /**
             * @description Machine code persisted to audit `metadata_json.failure_code`.
             * @example database_provision_failed
             */
            failureCode: string;
            /** @description Human-readable detail (no secrets). */
            reason?: string;
        };
        /**
         * @description System-of-record role for the launcher label (terminology §7), derived from
         *     catalog `provides`: `billing-api`→`billing`, `reconciliation-api`→
         *     `reconciliation_evidence`, `cms-api`→`cms`, `archive-api`→`archive`.
         * @enum {string}
         */
        SsotRole: "billing" | "reconciliation_evidence" | "cms" | "archive" | "none";
        InstalledApp: {
            catalogId: components["schemas"]["CatalogId"];
            name: string;
            /**
             * Format: uri
             * @description Public base URL (manifest `public_url`).
             */
            publicUrl: string;
            /** @description Per-app database name (manifest `database_name`). No credentials. */
            databaseName?: string | null;
            ssotRole: components["schemas"]["SsotRole"];
        };
        InstalledAppList: {
            apps: components["schemas"]["InstalledApp"][];
        };
        /**
         * @description Affected orchestration entity (audit-trail §4; matches `schema/suite-audit-event.schema.json`).
         * @enum {string}
         */
        AuditEntityType: "install_session" | "app_selection" | "disclaimer_acknowledgment" | "suite_env_config" | "app_database" | "integration_wiring" | "install_manifest" | "suite_org_profile" | "catalog_pin" | "apex_operator";
        /** @enum {string} */
        AuditSource: "installer_ui" | "installer_cli" | "apex_admin" | "system" | "api";
        /**
         * @description Read projection of one append-only audit row. snake_case persistence
         *     columns are mapped to camelCase here: `before`→`before_json`,
         *     `after`→`after_json`, `metadata`→`metadata_json`, `*Id`→`*_id`.
         *     Sanitized — secret-bearing values already appear as `"[REDACTED]"`
         *     (audit-trail §5).
         */
        SuiteAuditEvent: {
            id: components["schemas"]["Ulid"];
            suiteId: components["schemas"]["Ulid"];
            orgExternalId?: components["schemas"]["Ulid"] | null;
            /** @description Apex user; null for pre-auth wizard / system events. */
            actorUserId?: components["schemas"]["Ulid"] | null;
            /** @description Display fallback only; no secrets. */
            actorLabel?: string | null;
            /**
             * @description `{entity}.{verb}`, registered in audit-trail §4.
             * @example install_session.completed
             */
            action: string;
            entityType: components["schemas"]["AuditEntityType"];
            entityId: string;
            /** @description Sanitized state before mutation (`before_json`); null on create. */
            before?: Record<string, never> | null;
            /** @description Sanitized state after mutation (`after_json`); null only if policy allows. */
            after?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            source: components["schemas"]["AuditSource"];
            /** @description Correlates with HTTP `X-Request-Id` when present. */
            requestId?: string | null;
            installSessionId?: components["schemas"]["Ulid"] | null;
            /** @description Event-specific extras (`metadata_json`); obeys audit-trail §5 sanitization. */
            metadata?: Record<string, never> | null;
        };
        SuiteAuditEventList: {
            items: components["schemas"]["SuiteAuditEvent"][];
            /** @description Opaque cursor for the next page, or null when no more rows. */
            nextCursor: string | null;
        };
        /** @description RFC 9457 Problem Details. `type` uses `https://nene-suite.dev/problems/{slug}`. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://nene-suite.dev/problems/install-session-not-found
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
        ValidationProblemDetails: components["schemas"]["ProblemDetails"] & {
            /** @description Structured field errors for `validation-failed` and related slugs. */
            errors: {
                /** @example selectedApps */
                field: string;
                /** @example dependency_unmet */
                code: string;
                detail?: string;
            }[];
        };
    };
    responses: {
        /** @description Authentication required or token invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://nene-suite.dev/problems/unauthorized",
                 *       "title": "Authentication required",
                 *       "status": 401,
                 *       "detail": "A valid apex operator token is required.",
                 *       "instance": "/api/v1/installed-apps"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description No install session with that id. */
        InstallSessionNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://nene-suite.dev/problems/install-session-not-found",
                 *       "title": "Install session not found",
                 *       "status": 404,
                 *       "detail": "No install session exists for id 01J8XR4ZS6Q9V2H7K3N5M0B8TC.",
                 *       "instance": "/api/v1/install-sessions/01J8XR4ZS6Q9V2H7K3N5M0B8TC"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Session is in a state that does not allow this transition. */
        InstallSessionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://nene-suite.dev/problems/install-session-conflict",
                 *       "title": "Install session conflict",
                 *       "status": 409,
                 *       "detail": "This install session is already completed and cannot be modified.",
                 *       "instance": "/api/v1/install-sessions/01J8XR4ZS6Q9V2H7K3N5M0B8TC/complete"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request body or parameters failed validation. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://nene-suite.dev/problems/validation-failed",
                 *       "title": "Validation failed",
                 *       "status": 422,
                 *       "detail": "One or more fields are invalid.",
                 *       "instance": "/api/v1/install-sessions",
                 *       "errors": [
                 *         {
                 *           "field": "tier",
                 *           "code": "invalid_enum",
                 *           "detail": "tier must be one of: B"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblemDetails"];
            };
        };
        /** @description Unexpected server error. No stack traces, SQL, paths, or secrets exposed. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://nene-suite.dev/problems/internal-error",
                 *       "title": "Internal server error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred. Please try again later.",
                 *       "instance": "/api/v1/install-sessions"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /**
         * @description ULID of the install session (maps to `install_session_id`).
         * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
         */
        InstallSessionId: components["schemas"]["Ulid"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "suiteMode": true,
                     *       "time": "2026-05-30T09:48:46Z"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    listCatalogApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "version": 1,
                     *       "apps": [
                     *         {
                     *           "id": "nene-invoice",
                     *           "name": "NeNe Invoice",
                     *           "repository": "hideyukiMORI/nene-invoice",
                     *           "path": "nene-invoice",
                     *           "status": "installable",
                     *           "requires": [],
                     *           "provides": [
                     *             "billing-api"
                     *           ],
                     *           "installEntry": "/install/index.php",
                     *           "databaseEnvPrefix": "NENE_INVOICE_DB_"
                     *         },
                     *         {
                     *           "id": "nene-clear",
                     *           "name": "NeNe Clear",
                     *           "repository": "hideyukiMORI/nene-clear",
                     *           "path": "nene-clear",
                     *           "status": "installable",
                     *           "requires": [
                     *             "nene-invoice"
                     *           ],
                     *           "provides": [
                     *             "reconciliation-api"
                     *           ],
                     *           "installEntry": "/install/index.php",
                     *           "databaseEnvPrefix": "NENE_CLEAR_DB_"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["CatalogAppList"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    startInstallSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "tier": "B",
                 *       "selectedApps": [
                 *         "nene-invoice",
                 *         "nene-clear"
                 *       ],
                 *       "orgDisplayName": "Example Organization"
                 *     }
                 */
                "application/json": components["schemas"]["StartInstallSessionRequest"];
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    /**
                     * @description Canonical URL of the created session.
                     * @example /api/v1/install-sessions/01J8XR4ZS6Q9V2H7K3N5M0B8TC
                     */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01J8XR4ZS6Q9V2H7K3N5M0B8TC",
                     *       "suiteId": "01J8XR0G7Q9V2H7K3N5M0B8TCA",
                     *       "status": "in_progress",
                     *       "tier": "B",
                     *       "catalogRevision": 1,
                     *       "selectedApps": [
                     *         "nene-invoice",
                     *         "nene-clear"
                     *       ],
                     *       "disclaimerAccepted": false,
                     *       "disclaimerAcceptedAt": null,
                     *       "orgExternalId": null,
                     *       "orgDisplayName": "Example Organization",
                     *       "installManifestId": null,
                     *       "failureCode": null,
                     *       "createdAt": "2026-05-30T09:48:46Z",
                     *       "updatedAt": "2026-05-30T09:48:46Z",
                     *       "completedAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["InstallSession"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["ServerError"];
        };
    };
    getInstallSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID of the install session (maps to `install_session_id`).
                 * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
                 */
                installSessionId: components["parameters"]["InstallSessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01J8XR4ZS6Q9V2H7K3N5M0B8TC",
                     *       "suiteId": "01J8XR0G7Q9V2H7K3N5M0B8TCA",
                     *       "status": "in_progress",
                     *       "tier": "B",
                     *       "catalogRevision": 1,
                     *       "selectedApps": [
                     *         "nene-invoice",
                     *         "nene-clear"
                     *       ],
                     *       "disclaimerAccepted": true,
                     *       "disclaimerAcceptedAt": "2026-05-30T09:50:00Z",
                     *       "orgExternalId": null,
                     *       "orgDisplayName": "Example Organization",
                     *       "installManifestId": null,
                     *       "failureCode": null,
                     *       "createdAt": "2026-05-30T09:48:46Z",
                     *       "updatedAt": "2026-05-30T09:50:00Z",
                     *       "completedAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["InstallSession"];
                };
            };
            404: components["responses"]["InstallSessionNotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    updateAppSelection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID of the install session (maps to `install_session_id`).
                 * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
                 */
                installSessionId: components["parameters"]["InstallSessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "selectedApps": [
                 *         "nene-clear"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["UpdateAppSelectionRequest"];
            };
        };
        responses: {
            /** @description Selection updated (dependencies resolved into `selectedApps`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01J8XR4ZS6Q9V2H7K3N5M0B8TC",
                     *       "suiteId": "01J8XR0G7Q9V2H7K3N5M0B8TCA",
                     *       "status": "in_progress",
                     *       "tier": "B",
                     *       "catalogRevision": 1,
                     *       "selectedApps": [
                     *         "nene-invoice",
                     *         "nene-clear"
                     *       ],
                     *       "disclaimerAccepted": false,
                     *       "disclaimerAcceptedAt": null,
                     *       "orgExternalId": null,
                     *       "orgDisplayName": "Example Organization",
                     *       "installManifestId": null,
                     *       "failureCode": null,
                     *       "createdAt": "2026-05-30T09:48:46Z",
                     *       "updatedAt": "2026-05-30T09:49:10Z",
                     *       "completedAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["InstallSession"];
                };
            };
            404: components["responses"]["InstallSessionNotFound"];
            409: components["responses"]["InstallSessionConflict"];
            /**
             * @description Validation failed. Common slugs: `validation-failed` (bad shape),
             *     `dependency-unmet` (a required app was omitted),
             *     `app-not-installable` (a `planned`/`deprecated` app was selected).
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    acceptDisclaimer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID of the install session (maps to `install_session_id`).
                 * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
                 */
                installSessionId: components["parameters"]["InstallSessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "disclaimerVersion": "2026-05-29",
                 *       "acceptedLabel": "operator@example.com"
                 *     }
                 */
                "application/json": components["schemas"]["AcceptDisclaimerRequest"];
            };
        };
        responses: {
            /** @description Acceptance recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01J8XR4ZS6Q9V2H7K3N5M0B8TC",
                     *       "suiteId": "01J8XR0G7Q9V2H7K3N5M0B8TCA",
                     *       "status": "in_progress",
                     *       "tier": "B",
                     *       "catalogRevision": 1,
                     *       "selectedApps": [
                     *         "nene-invoice",
                     *         "nene-clear"
                     *       ],
                     *       "disclaimerAccepted": true,
                     *       "disclaimerAcceptedAt": "2026-05-30T09:50:00Z",
                     *       "orgExternalId": null,
                     *       "orgDisplayName": "Example Organization",
                     *       "installManifestId": null,
                     *       "failureCode": null,
                     *       "createdAt": "2026-05-30T09:48:46Z",
                     *       "updatedAt": "2026-05-30T09:50:00Z",
                     *       "completedAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["InstallSession"];
                };
            };
            404: components["responses"]["InstallSessionNotFound"];
            409: components["responses"]["InstallSessionConflict"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["ServerError"];
        };
    };
    completeInstallSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID of the install session (maps to `install_session_id`).
                 * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
                 */
                installSessionId: components["parameters"]["InstallSessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session completed; manifest written. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01J8XR4ZS6Q9V2H7K3N5M0B8TC",
                     *       "suiteId": "01J8XR0G7Q9V2H7K3N5M0B8TCA",
                     *       "status": "completed",
                     *       "tier": "B",
                     *       "catalogRevision": 1,
                     *       "selectedApps": [
                     *         "nene-invoice",
                     *         "nene-clear"
                     *       ],
                     *       "disclaimerAccepted": true,
                     *       "disclaimerAcceptedAt": "2026-05-30T09:50:00Z",
                     *       "orgExternalId": "01J8XR0G7Q9V2H7K3N5M0BRZX9",
                     *       "orgDisplayName": "Example Organization",
                     *       "installManifestId": "01J8XR9MAQ9V2H7K3N5M0B8DFG",
                     *       "failureCode": null,
                     *       "createdAt": "2026-05-30T09:48:46Z",
                     *       "updatedAt": "2026-05-30T09:51:30Z",
                     *       "completedAt": "2026-05-30T09:51:30Z"
                     *     }
                     */
                    "application/json": components["schemas"]["InstallSession"];
                };
            };
            404: components["responses"]["InstallSessionNotFound"];
            409: components["responses"]["InstallSessionConflict"];
            /**
             * @description Pre-conditions unmet. Common slugs: `disclaimer-not-accepted` (R-04),
             *     `no-apps-selected`.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    failInstallSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID of the install session (maps to `install_session_id`).
                 * @example 01J8XR4ZS6Q9V2H7K3N5M0B8TC
                 */
                installSessionId: components["parameters"]["InstallSessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "failureCode": "database_provision_failed",
                 *       "reason": "Could not create database for nene-clear."
                 *     }
                 */
                "application/json": components["schemas"]["FailInstallSessionRequest"];
            };
        };
        responses: {
            /** @description Session marked failed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01J8XR4ZS6Q9V2H7K3N5M0B8TC",
                     *       "suiteId": "01J8XR0G7Q9V2H7K3N5M0B8TCA",
                     *       "status": "failed",
                     *       "tier": "B",
                     *       "catalogRevision": 1,
                     *       "selectedApps": [
                     *         "nene-invoice",
                     *         "nene-clear"
                     *       ],
                     *       "disclaimerAccepted": true,
                     *       "disclaimerAcceptedAt": "2026-05-30T09:50:00Z",
                     *       "orgExternalId": null,
                     *       "orgDisplayName": "Example Organization",
                     *       "installManifestId": null,
                     *       "failureCode": "database_provision_failed",
                     *       "createdAt": "2026-05-30T09:48:46Z",
                     *       "updatedAt": "2026-05-30T09:51:00Z",
                     *       "completedAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["InstallSession"];
                };
            };
            404: components["responses"]["InstallSessionNotFound"];
            409: components["responses"]["InstallSessionConflict"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["ServerError"];
        };
    };
    listInstalledApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installed apps. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "apps": [
                     *         {
                     *           "catalogId": "nene-invoice",
                     *           "name": "NeNe Invoice",
                     *           "publicUrl": "https://example.com/nene-invoice/",
                     *           "databaseName": "nene_invoice",
                     *           "ssotRole": "billing"
                     *         },
                     *         {
                     *           "catalogId": "nene-clear",
                     *           "name": "NeNe Clear",
                     *           "publicUrl": "https://example.com/nene-clear/",
                     *           "databaseName": "nene_clear",
                     *           "ssotRole": "reconciliation_evidence"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["InstalledAppList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ServerError"];
        };
    };
    listSuiteAuditEvents: {
        parameters: {
            query?: {
                /** @description Filter to events grouped under one install run. */
                installSessionId?: components["schemas"]["Ulid"];
                /**
                 * @description Filter by audit action (`{entity}.{verb}`), audit-trail §4.
                 * @example install_session.completed
                 */
                action?: string;
                /** @description Page size. */
                limit?: number;
                /** @description Opaque pagination cursor from a prior `nextCursor`. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of audit events (newest first). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "01J8XRADTQ9V2H7K3N5M0B8QGH",
                     *           "suiteId": "01J8XR0G7Q9V2H7K3N5M0B8TCA",
                     *           "orgExternalId": "01J8XR0G7Q9V2H7K3N5M0BRZX9",
                     *           "actorUserId": null,
                     *           "actorLabel": "operator@example.com",
                     *           "action": "disclaimer.accepted",
                     *           "entityType": "disclaimer_acknowledgment",
                     *           "entityId": "01J8XR4ZS6Q9V2H7K3N5M0B8TC",
                     *           "before": null,
                     *           "after": {
                     *             "disclaimerVersion": "2026-05-29",
                     *             "acceptedAt": "2026-05-30T09:50:00Z"
                     *           },
                     *           "createdAt": "2026-05-30T09:50:00Z",
                     *           "source": "installer_ui",
                     *           "requestId": "7f3a9c2e-0b1d-4c8a-9e2f-1a2b3c4d5e6f",
                     *           "installSessionId": "01J8XR4ZS6Q9V2H7K3N5M0B8TC",
                     *           "metadata": null
                     *         }
                     *       ],
                     *       "nextCursor": null
                     *     }
                     */
                    "application/json": components["schemas"]["SuiteAuditEventList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["ServerError"];
        };
    };
    getAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated operator. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01J8XR0G7Q9V2H7K3N5M0B8TCA",
                     *       "email": "operator@example.com",
                     *       "displayName": "Example Operator"
                     *     }
                     */
                    "application/json": components["schemas"]["Operator"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ServerError"];
        };
    };
    createAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "operator@example.com",
                 *       "password": "••••••••"
                 *     }
                 */
                "application/json": components["schemas"]["CreateAuthSessionRequest"];
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.payload.signature",
                     *       "expiresAt": "2026-05-30T11:48:46Z",
                     *       "operator": {
                     *         "id": "01J8XR0G7Q9V2H7K3N5M0B8TCA",
                     *         "email": "operator@example.com",
                     *         "displayName": "Example Operator"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Invalid email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://nene-suite.dev/problems/invalid-credentials",
                     *       "title": "Invalid credentials",
                     *       "status": 401,
                     *       "detail": "Invalid email or password.",
                     *       "instance": "/api/v1/auth/session"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["ServerError"];
        };
    };
    deleteAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended; no content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ServerError"];
        };
    };
}
